// <auto-generated />
using System;
using Blizka.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blizka.Data.Migrations
{
    [DbContext(typeof(BlizkaDbContext))]
    [Migration("20260819091343_AddUserConsent")]
    partial class AddUserConsent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blizka.App.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Point>("Coordinates")
                        .IsRequired()
                        .HasColumnType("geography (Point, 4326)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<string>("NameBe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("NameBe");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NameBe"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NameBe"), new[] { "gin_trgm_ops" });

                    b.HasIndex("NameEn");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NameEn"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NameEn"), new[] { "gin_trgm_ops" });

                    b.HasIndex("NameRu");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NameRu"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NameRu"), new[] { "gin_trgm_ops" });

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000001"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (27.559 53.9006)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Мінск",
                            NameEn = "Minsk",
                            NameRu = "Минск"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000002"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (30.9754 52.4345)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Гомель",
                            NameEn = "Homyel",
                            NameRu = "Гомель"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000003"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (30.3313 53.9007)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Магілёў",
                            NameEn = "Mahilyow",
                            NameRu = "Могилёв"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000004"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (30.2049 55.1904)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Віцебск",
                            NameEn = "Vitsyebsk",
                            NameRu = "Витебск"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000005"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (23.8258 53.6884)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Гродна",
                            NameEn = "Hrodna",
                            NameRu = "Гродно"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000006"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (23.7341 52.0975)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Брэст",
                            NameEn = "Brest",
                            NameRu = "Брест"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000007"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.2167 53.15)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Бабруйск",
                            NameEn = "Babruysk",
                            NameRu = "Бобруйск"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000008"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.0167 53.1333)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Баранавічы",
                            NameEn = "Baranavichy",
                            NameRu = "Барановичи"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000009"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (28.5 54.2333)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Барысаў",
                            NameEn = "Barysaw",
                            NameRu = "Борисов"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000010"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.0985 52.1216)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Пінск",
                            NameEn = "Pinsk",
                            NameRu = "Пинск"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000011"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (30.4172 54.5081)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Орша",
                            NameEn = "Orsha",
                            NameRu = "Орша"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000012"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.2411 52.0498)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Мазыр",
                            NameEn = "Mazyr",
                            NameRu = "Мозырь"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000013"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (27.5442 52.7975)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Салігорск",
                            NameEn = "Salihorsk",
                            NameRu = "Солигорск"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000014"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (28.65 55.5333)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Наваполацк",
                            NameEn = "Navapolatsk",
                            NameRu = "Новополоцк"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000015"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (25.3 53.8833)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Ліда",
                            NameEn = "Lida",
                            NameRu = "Лида"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000016"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.85 54.3167)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Маладзечна",
                            NameEn = "Maladzyechna",
                            NameRu = "Молодечно"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000017"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (28.7833 55.4833)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Полацк",
                            NameEn = "Polatsk",
                            NameRu = "Полоцк"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000018"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (30.035 52.8925)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Жлобін",
                            NameEn = "Zhlobin",
                            NameRu = "Жлобин"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000019"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (29.7333 52.6333)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Светлагорск",
                            NameEn = "Svyetlahorsk",
                            NameRu = "Светлогорск"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000020"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (30.4 52.3667)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Рэчыца",
                            NameEn = "Rechytsa",
                            NameRu = "Речица"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000021"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (27.55 53.0167)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Слуцк",
                            NameEn = "Slutsk",
                            NameRu = "Слуцк"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000022"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (24.3667 52.2136)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Кобрын",
                            NameEn = "Kobryn",
                            NameRu = "Кобрин"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000023"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (25.3197 53.0925)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Слонім",
                            NameEn = "Slonim",
                            NameRu = "Слоним"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000024"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (24.4611 53.1633)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Ваўкавыск",
                            NameEn = "Vawkavysk",
                            NameRu = "Волковыск"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000025"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (28.3333 54.1)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Жодзіна",
                            NameEn = "Zhodzina",
                            NameRu = "Жодино"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000026"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (25.8258 53.5989)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Навагрудак",
                            NameEn = "Navahrudak",
                            NameRu = "Новогрудок"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000027"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (27.1333 53.6833)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Дзяржынск",
                            NameEn = "Dzyarzhynsk",
                            NameRu = "Дзержинск"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a02-000000000028"),
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.9169 54.4914)"),
                            Country = "BY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsOpen = true,
                            NameBe = "Вілейка",
                            NameEn = "Vileyka",
                            NameRu = "Вилейка"
                        });
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.CityWaitlist", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("NotifyOnOpen")
                        .HasColumnType("boolean");

                    b.HasKey("CityId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CityWaitlists");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.DatePreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameBe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DatePreferences");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a03-000000000001"),
                            Code = "ActiveOutdoors",
                            NameBe = "Актыўны адпачынак на прыродзе",
                            NameEn = "Active outdoors",
                            NameRu = "Активный отдых на природе"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a03-000000000002"),
                            Code = "CalmHangout",
                            NameBe = "Спакойныя пасядзелкі",
                            NameEn = "Calm hangout",
                            NameRu = "Спокойные посиделки"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a03-000000000003"),
                            Code = "QuizzesBoardGames",
                            NameBe = "Квізы і настольныя гульні",
                            NameEn = "Quizzes & board games",
                            NameRu = "Квизы и настольные игры"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a03-000000000004"),
                            Code = "SomethingNew",
                            NameBe = "Штосьці новае",
                            NameEn = "Something new",
                            NameRu = "Что-то новое"
                        });
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.Idea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VotesCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.ToTable("Ideas");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.IdeaVote", b =>
                {
                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdeaId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("IdeaVotes");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.Interest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("boolean");

                    b.Property<string>("NameBe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000001"),
                            Category = "Sport",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Бег",
                            NameEn = "Running",
                            NameRu = "Бег"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000002"),
                            Category = "Sport",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Ёга",
                            NameEn = "Yoga",
                            NameRu = "Йога"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000003"),
                            Category = "Sport",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Трэнажорная зала",
                            NameEn = "Gym",
                            NameRu = "Тренажёрный зал"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000004"),
                            Category = "Sport",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Веласпорт",
                            NameEn = "Cycling",
                            NameRu = "Велоспорт"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000005"),
                            Category = "Sport",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Плаванне",
                            NameEn = "Swimming",
                            NameRu = "Плавание"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000006"),
                            Category = "Sport",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Турызм і паходы",
                            NameEn = "Hiking",
                            NameRu = "Туризм и походы"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000007"),
                            Category = "Sport",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Танцы",
                            NameEn = "Dancing",
                            NameRu = "Танцы"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000008"),
                            Category = "Sport",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Баявыя мастацтвы",
                            NameEn = "Martial Arts",
                            NameRu = "Боевые искусства"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000009"),
                            Category = "Creativity",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Музыка",
                            NameEn = "Music",
                            NameRu = "Музыка"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000010"),
                            Category = "Creativity",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Маляванне",
                            NameEn = "Drawing",
                            NameRu = "Рисование"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000011"),
                            Category = "Creativity",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Фатаграфія",
                            NameEn = "Photography",
                            NameRu = "Фотография"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000012"),
                            Category = "Creativity",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Кіно",
                            NameEn = "Movies",
                            NameRu = "Кино"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000013"),
                            Category = "Creativity",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Тэатр",
                            NameEn = "Theatre",
                            NameRu = "Театр"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000014"),
                            Category = "Creativity",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Пісьменства",
                            NameEn = "Writing",
                            NameRu = "Писательство"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000015"),
                            Category = "Creativity",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Дызайн",
                            NameEn = "Design",
                            NameRu = "Дизайн"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000016"),
                            Category = "Creativity",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Рукадзелле",
                            NameEn = "Handicraft",
                            NameRu = "Рукоделие"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000017"),
                            Category = "Entertainment",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Настольныя гульні",
                            NameEn = "Board Games",
                            NameRu = "Настольные игры"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000018"),
                            Category = "Entertainment",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Відэагульні",
                            NameEn = "Video Games",
                            NameRu = "Видеоигры"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000019"),
                            Category = "Entertainment",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Караоке",
                            NameEn = "Karaoke",
                            NameRu = "Караоке"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000020"),
                            Category = "Entertainment",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Стэндап",
                            NameEn = "Stand-up",
                            NameRu = "Стендап"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000021"),
                            Category = "Entertainment",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Вечарынкі",
                            NameEn = "Parties",
                            NameRu = "Вечеринки"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000022"),
                            Category = "Entertainment",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Квэсты",
                            NameEn = "Escape Rooms",
                            NameRu = "Квесты"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000023"),
                            Category = "Entertainment",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Аніме",
                            NameEn = "Anime",
                            NameRu = "Аниме"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000024"),
                            Category = "Entertainment",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Серыялы",
                            NameEn = "TV Shows",
                            NameRu = "Сериалы"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000025"),
                            Category = "FoodAndDrinks",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Кулінарыя",
                            NameEn = "Cooking",
                            NameRu = "Кулинария"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000026"),
                            Category = "FoodAndDrinks",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Кава",
                            NameEn = "Coffee",
                            NameRu = "Кофе"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000027"),
                            Category = "FoodAndDrinks",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Віно",
                            NameEn = "Wine",
                            NameRu = "Вино"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000028"),
                            Category = "FoodAndDrinks",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Крафтавае піва",
                            NameEn = "Craft Beer",
                            NameRu = "Крафтовое пиво"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000029"),
                            Category = "FoodAndDrinks",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Веганская ежа",
                            NameEn = "Vegan Food",
                            NameRu = "Веганская еда"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000030"),
                            Category = "FoodAndDrinks",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Рэстараны",
                            NameEn = "Restaurants",
                            NameRu = "Рестораны"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000031"),
                            Category = "FoodAndDrinks",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Выпечка",
                            NameEn = "Baking",
                            NameRu = "Выпечка"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000032"),
                            Category = "FoodAndDrinks",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Стрытфуд",
                            NameEn = "Street Food",
                            NameRu = "Стритфуд"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000033"),
                            Category = "GrowthAndTravel",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Падарожжы",
                            NameEn = "Travel",
                            NameRu = "Путешествия"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000034"),
                            Category = "GrowthAndTravel",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Чытанне",
                            NameEn = "Reading",
                            NameRu = "Чтение"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000035"),
                            Category = "GrowthAndTravel",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Мовы",
                            NameEn = "Languages",
                            NameRu = "Языки"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000036"),
                            Category = "GrowthAndTravel",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Медытацыя",
                            NameEn = "Meditation",
                            NameRu = "Медитация"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000037"),
                            Category = "GrowthAndTravel",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Псіхалогія",
                            NameEn = "Psychology",
                            NameRu = "Психология"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000038"),
                            Category = "GrowthAndTravel",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Валанцёрства",
                            NameEn = "Volunteering",
                            NameRu = "Волонтёрство"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000039"),
                            Category = "GrowthAndTravel",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Навука",
                            NameEn = "Science",
                            NameRu = "Наука"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0a01-000000000040"),
                            Category = "GrowthAndTravel",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCustom = false,
                            NameBe = "Стартапы",
                            NameEn = "Startups",
                            NameRu = "Стартапы"
                        });
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ContactUnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ContactUnlockedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("MatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("MessageSentCheckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("User1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("User2Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContactUnlockedByUserId");

                    b.HasIndex("User2Id");

                    b.HasIndex("User1Id", "User2Id")
                        .IsUnique();

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.Minigame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<int[]>("DilemmaIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("Minigames");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.MinigameAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<char>("Choice")
                        .HasColumnType("character(1)");

                    b.Property<int>("DilemmaIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("MinigameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("MinigameId", "UserId", "DilemmaIndex")
                        .IsUnique();

                    b.ToTable("MinigameAnswers");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.OnboardingDraft", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Step")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("OnboardingDrafts");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<string>("MediumUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SortOrder");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.QuestionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.HasIndex("MatchId", "QuestionId", "UserId")
                        .IsUnique();

                    b.ToTable("QuestionAnswers");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.QuestionOfDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TextBe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextRu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("QuestionsOfDay");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReportedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReporterUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReporterUserId");

                    b.HasIndex("ReportedUserId", "CreatedAt");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.SparkTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("SparkTransactions");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CurrentPeriodEndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.Swipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UndoneAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ToUserId");

                    b.HasIndex("FromUserId", "ToUserId")
                        .IsUnique();

                    b.ToTable("Swipes");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.TelegramPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SparkAmount")
                        .HasColumnType("integer");

                    b.Property<int>("StarsAmount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelegramPaymentChargeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TelegramPaymentChargeId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("TelegramPayments");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Chronotype")
                        .HasColumnType("text");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletenessBonus100AwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletenessBonus60AwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletenessBonus80AwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Coordinates")
                        .HasColumnType("geography (Point, 4326)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DatingGoal")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Drinking")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("InstagramHandle")
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LikesRevealed")
                        .HasColumnType("boolean");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("ProfileCompleteness")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Prompts")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Smoking")
                        .HasColumnType("text");

                    b.Property<int>("SparksBalance")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VoiceIntroUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.UserConsent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Type");

                    b.ToTable("UserConsents");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.UserDatePreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DatePreferenceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "DatePreferenceId");

                    b.HasIndex("DatePreferenceId");

                    b.ToTable("UserDatePreferences");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.UserInterest", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InterestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("UserInterests");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.CityWaitlist", b =>
                {
                    b.HasOne("Blizka.App.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blizka.App.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.Idea", b =>
                {
                    b.HasOne("Blizka.App.Domain.Entities.User", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthorUser");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.IdeaVote", b =>
                {
                    b.HasOne("Blizka.App.Domain.Entities.Idea", "Idea")
                        .WithMany("Votes")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blizka.App.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.Match", b =>
                {
                    b.HasOne("Blizka.App.Domain.Entities.User", "ContactUnlockedByUser")
                        .WithMany()
                        .HasForeignKey("ContactUnlockedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Blizka.App.Domain.Entities.User", "User1")
                        .WithMany()
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Blizka.App.Domain.Entities.User", "User2")
                        .WithMany()
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContactUnlockedByUser");

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.Minigame", b =>
                {
                    b.HasOne("Blizka.App.Domain.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.MinigameAnswer", b =>
                {
                    b.HasOne("Blizka.App.Domain.Entities.Minigame", "Minigame")
                        .WithMany()
                        .HasForeignKey("MinigameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blizka.App.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Minigame");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.OnboardingDraft", b =>
                {
                    b.HasOne("Blizka.App.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("Blizka.App.Domain.Entities.OnboardingDraft", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.Photo", b =>
                {
                    b.HasOne("Blizka.App.Domain.Entities.User", "User")
                        .WithMany("Photos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.QuestionAnswer", b =>
                {
                    b.HasOne("Blizka.App.Domain.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Blizka.App.Domain.Entities.QuestionOfDay", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Blizka.App.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.Report", b =>
                {
                    b.HasOne("Blizka.App.Domain.Entities.User", "ReportedUser")
                        .WithMany()
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Blizka.App.Domain.Entities.User", "ReporterUser")
                        .WithMany()
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportedUser");

                    b.Navigation("ReporterUser");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.SparkTransaction", b =>
                {
                    b.HasOne("Blizka.App.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("Blizka.App.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.Swipe", b =>
                {
                    b.HasOne("Blizka.App.Domain.Entities.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Blizka.App.Domain.Entities.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.TelegramPayment", b =>
                {
                    b.HasOne("Blizka.App.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.User", b =>
                {
                    b.HasOne("Blizka.App.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.UserConsent", b =>
                {
                    b.HasOne("Blizka.App.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.UserDatePreference", b =>
                {
                    b.HasOne("Blizka.App.Domain.Entities.DatePreference", "DatePreference")
                        .WithMany("UserDatePreferences")
                        .HasForeignKey("DatePreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blizka.App.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatePreference");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.UserInterest", b =>
                {
                    b.HasOne("Blizka.App.Domain.Entities.Interest", "Interest")
                        .WithMany("UserInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blizka.App.Domain.Entities.User", "User")
                        .WithMany("UserInterests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.DatePreference", b =>
                {
                    b.Navigation("UserDatePreferences");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.Idea", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.Interest", b =>
                {
                    b.Navigation("UserInterests");
                });

            modelBuilder.Entity("Blizka.App.Domain.Entities.User", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("UserInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
